In [68]:
import pandas as pd
import numpy as np
import os
from sklearn.svm import SVC
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn import svm
from sklearn.svm import LinearSVC
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.svm import SVC
from numpy import mean

In [2]:
os.chdir(r'\Users\hossa084\Downloads\wildfire\WildFires-master')

In [10]:

#creating a function to download a zip and unzip it in my desired location
def download_data(dw_url,destination):
    import wget
    import zipfile
    
    filename = wget.download(dw_url)
    print("Successfully downloaded", filename)
    
    with zipfile.ZipFile(destination + "/" + filename, 'r') as zip_ref:
        zip_ref.extractall(destination)

In [11]:
#using my function
download_data('https://github.com/ouladsayadyounes/WildFires/archive/refs/heads/master.zip',r'\Users\hossa084\Downloads\wildfire\WildFires-master')

-1 / unknownSuccessfully downloaded WildFires-master.zip


In [3]:
#opening the CSV and viewing part of it
wildfires = pd.read_csv('WildFires-master/WildFires_DataSet.csv', float_precision='high')
wildfires.head()

NDVI           LST  BURNED_AREA    CLASS
0  0.506782  14584.272727     4.692308  no_fire
1  0.522150  14655.833333     5.000000  no_fire
2  0.682284  14780.000000     5.000000     fire
3  0.120046  13298.500000     3.500000  no_fire
4  0.568734  14743.000000     5.000000  no_fire

In [4]:
#ML does not like classes that are a string
#change the classes to numbers
wildfires['CLASS'] = wildfires['CLASS'].map({'fire': 1, 'no_fire': 0})

In [7]:
#seperating the features from the labels
wildfire_features = wildfires.copy()
wildfire_labels = wildfire_features.pop('CLASS')
wildfire_labels.head()



0    0
1    0
2    1
3    0
4    0
Name: CLASS, dtype: int64

In [8]:
#create functions to normalize the data for the Neural Net
def normalize(x):
    x_med = x.median()
    x_std = x.std()
    x = ((x-x_med)/x_std)
    return x

def normalize_dataframe(pandas_df):
    pandas_df = pandas_df.apply(normalize)
    
    return pandas_df

In [9]:
wildfire_features = normalize_dataframe(wildfire_features) 
wildfire_features.head()
#now you might be thinking to yourself, "That's shome pretty shweet data"

NDVI       LST  BURNED_AREA
0 -0.628978 -0.167546    -0.391111
1 -0.463460  0.027480     0.135948
2  1.261242  0.365876     0.135948
3 -4.794266 -3.671703    -2.433466
4  0.038267  0.265038     0.135948

In [10]:

#changing this from a series to values
wildfire_labels.values


array([0, 0, 1, ..., 1, 0, 1], dtype=int64)

In [11]:
wildfire_features = np.array(wildfire_features)
wildfire_features

array([[-6.28978449e-01, -1.67545939e-01, -3.91111091e-01],
       [-4.63459505e-01,  2.74804235e-02,  1.35947705e-01],
       [ 1.26124186e+00,  3.65875733e-01,  1.35947705e-01],
       ...,
       [ 5.15028005e-01,  2.88203790e-01, -3.28993790e+00],
       [ 5.30871209e-01, -2.82003661e+00,  7.16010091e-04],
       [-1.68922379e-01, -1.02464888e+00,  1.35947705e-01]])

In [24]:
#splitting my features and labels into train and test
wf_features_train, wf_features_test, wf_class_train, wf_class_test = model_selection.train_test_split(wildfire_features, wildfire_labels, test_size=0.3)

In [47]:
clf = svm.SVC()
clf.fit(wf_features_train, wf_class_train)

SVC()

In [55]:
y_pred = clf.predict(wf_features_test)
y_pred[:10],wf_class_test[:10]

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 1246    0
 1582    0
 1356    0
 1378    0
 538     0
 917     0
 1035    1
 455     0
 50      0
 735     1
 Name: CLASS, dtype: int64)

In [49]:
for i in y_pred:
    if i > .5:
        print("Fire")
    else:
        print("No fire")

No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire
No fire


In [56]:
#clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(wf_features_train, wf_class_train)

print(clf.predict([[1.261242,0.365876,0.135948]]))

[0]


In [67]:
from sklearn.metrics import classification_report
# fit a SVM model to the data
model = SVC()
model.fit(wildfire_features, wildfire_labels)
print(model)
# make predictions
expected = wildfire_labels
predicted = model.predict(wildfire_features)
# summarize the fit of the model
print(classification_report(expected, predicted))


SVC()
              precision    recall  f1-score   support

           0       0.79      0.99      0.88      1327
           1       0.77      0.08      0.14       386

    accuracy                           0.79      1713
   macro avg       0.78      0.54      0.51      1713
weighted avg       0.78      0.79      0.71      1713



In [63]:
# define evaluation procedure 
clf = svm.SVC(gamma='scale')
clf.fit(wf_features_train, wf_class_train)

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=300, random_state=1)
# evaluate model
scores = cross_val_score(clf, wf_features_train, wf_class_train, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.3f' % mean(scores))

Mean ROC AUC: 0.658


In [41]:
# get number of support vectors for each class
clf.n_support_

array([304, 264])

In [37]:
# get support vectors
clf.support_vectors_

array([[-0.62526267,  0.66932728, -1.99046352],
       [ 0.46298561,  0.42332285,  0.13594771],
       [ 0.32241083,  1.09157443, -0.82011419],
       ...,
       [-1.91840635,  0.34006572, -0.45352216],
       [-0.75809356,  1.10543156, -0.2119938 ],
       [-0.66389597, -0.17833887, -0.19861058]])

In [40]:
# get indices of support vectors
clf.support_

array([   6,    9,   12,   15,   17,   25,   34,   37,   38,   39,   40,
         41,   50,   56,   63,   70,   72,   77,   80,   85,   91,   95,
         99,  100,  103,  112,  119,  125,  134,  135,  138,  139,  149,
        156,  158,  161,  166,  172,  174,  178,  184,  186,  187,  188,
        193,  201,  205,  207,  211,  213,  214,  215,  219,  227,  228,
        231,  233,  236,  241,  242,  244,  247,  249,  250,  257,  263,
        264,  267,  268,  276,  283,  285,  298,  300,  302,  308,  317,
        320,  321,  328,  330,  343,  345,  347,  354,  359,  360,  361,
        362,  365,  374,  380,  383,  385,  391,  392,  401,  406,  408,
        413,  417,  424,  435,  436,  438,  443,  444,  445,  448,  452,
        464,  467,  470,  479,  482,  483,  486,  490,  495,  500,  502,
        503,  505,  526,  530,  534,  540,  541,  545,  547,  548,  549,
        556,  559,  566,  567,  576,  577,  583,  586,  596,  601,  603,
        607,  612,  613,  616,  619,  620,  621,  6